[alarm_rule]
alarmRuleId = "TEST_001"
alarmRuleName = "测试规则"
alarmClazz = "DEVICE_ALARM"
alarmLevel = "LOW"
enabled = 1
startTime = "00:00"
endTime = "23:59"

[[device_alarm_config.singlePropertyRule]]
symbol = "OR"
property = "t1"
lowValue = 1
expression1 = "lt"
highValue = 10
expression2 = "gt"

[[device_alarm_config.singlePropertyRule]]
symbol = "OR"
property = "t2"
lowValue = 5
expression1 = "lt"
highValue = 20
expression2 = "gt"

[[device_alarm_config.doublePropertyRule]]
symbol = "AND"
leftProperty = "t1"
rightProperty = "t2"
expression = "lt"

[device_alarm_config.frequency]
enabled = 1
hasAccumulate = 1
accumulateCount = 3
accumulateTimeRange = 30
